CREATE TABLE users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    email VARCHAR(100),
    password VARCHAR(100)
);


CREATE TABLE projects
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    user_id BIGINT,
    CONSTRAINT fk_project_user FOREIGN KEY (user_id) REFERENCES users(id)

);

CREATE TABLE task_lists
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(25),
    project_id BIGINT,
    CONSTRAINT fk_task_lists_project FOREIGN KEY (project_id) REFERENCES projects(id)

);
CREATE TABLE tasks
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(25),
    description VARCHAR(25),
    completed BOOLEAN DEFAULT FALSE,
    date_of_creation TIMESTAMP,
    deadline TIMESTAMP,
    task_list_id BIGINT,
    CONSTRAINT fk_tasks_tasklist FOREIGN KEY (task_list_id) REFERENCES task_lists(id)
);

CREATE TABLE comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(100),
    date_of_creation TIMESTAMP,
    user_id BIGINT,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id),
    task_id BIGINT,
    CONSTRAINT fk_comments_task FOREIGN KEY (task_id) REFERENCES tasks(id)


);


-- DROP TABLE comments;
-- DROP TABLE tasks;
-- DROP TABLE task_lists;
-- DROP TABLE projects;
-- DROP TABLE users;